### ISSUE TITLE
How to create /catergory-slug/post-slug

### ISSUE THREAD

**Issue by a-s-f** [oskarrough/ember-wordpress#20]
I was wondering if its possible to set up my project with some different routes, 
I am ember newbie with this project as I try to rebuild my portfolio, I do a bunch of various types of projects  I wanted to use wordpress cat. terms to organize my posts out to something like this 
example.com/design/design-post-slug
example.com/development/development-post-slug

is that possible or do I have to go 
example.com/catergories/design/design-post-slug
example.com/catergories/development/development-post-slug?

**Comment by sheriffderek** [comment]
This is more of a general Ember question and not specific to this addon. What this addon does, is set you up with some conventions so that you can get the WordPress data into _ember-data_ and then use it as ember expects.

You can make any routes you want, and then show whatever data you want there. In your case, it sounds like you may have Custom Post types? There is a note about extending the base post type for that. Then you'll need to make corresponding models for those post types. Or maybe just categories and standard posts? You definitely do not need to use /categories. The dummy app is just trying to show you some usual WordPress patterns ~ and show you the extent of what it can currently do. There are notes in the readme for querying by category.

As far as slugs, that is a little tricky depending on how you do it.

If you'd like, I could help walk you through it on screen-hero or something.
